language: python
python:
  - "3.5"
  - "3.6"
  # PyPy versions
  - "pypy3.5"
before_script:
  - git clone https://github.com/G2CView/genome-properties.git
script:
  - nosetests -v ./
  - ./test_parse_genome_properties_file.py  -i ./genome-properties/flatfiles/genomeProperties.txt
  - ./testing/test_end_to_end.sh

